### ISSUE TITLE
0.19.12 cant login after upgrade from 0.19.11

### ISSUE THREAD

**Issue by pallebone** [LemmyNet/lemmy-ui#3206]
### Requirements

- [x] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [x] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [x] It's a single bug. Do not report multiple bugs in one issue.
- [x] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

Scenario: 
lemmy.myserv.one running FE and BE 0.19.11.
Changed docker-compose.yml to have lemmy and lemmy-ui 0.19.12
Pull images and restart docker containers.
lemmy shows its now on 0.19.12

Issue:
No longer able to login. If already logged in then user can continue to interact with lemmy. If you log out or open a private browser window you cant login anymore.

Errors are below:
(TypeError: Load failed ---> Chrome/webkit)
(TypeError: NetworkError when attempting to fetch resource ----> Firefox)

### Steps to Reproduce

1. Upgrade to 0.19.12
2. Open private window in browser (to avoid using cache etc).
3. Cannot login (see error)

### Technical Details

![Image](https://github.com/user-attachments/assets/08e1ce48-4c43-483b-9d95-55f3988fe338)

![Image](https://github.com/user-attachments/assets/a06f5b74-e2c5-4f82-b1bb-8c7570dd36e2)

No errors I could find in logs, not sure how to troubleshoot.

### Lemmy Instance Version

0.19.12

### Lemmy Instance URL

lemmy.myserv.one

**Comment by pallebone** [comment]
I have reverted to a 0.19.11 snapshot but if given appropriate steps I can upgrade again or try whatever you want me to, just had no clue what to do and could find no errors after upgrading and was stuck.

**Comment by dessalines** [comment]
A lemmy-ui env var changed: make sure these are correct, especially `LEMMY_UI_LEMMY_EXTERNAL_HOST`

https://github.com/LemmyNet/lemmy-ansible/blob/main/examples/vars.yml#L42

If that fails I'll need to see your dockerfile (with passwords removed).

**Comment by pallebone** [comment]
Hello @dessalines 

Firstly let me thank you for taking the time to reply to me on a Sunday. It is appreciated.

I was unclear what changed exactly in the link you showed me/did not understand what I was to look at.

However here is my docker file (see below).

Based on what you are telling me, it seems this line is no longer valid?
LEMMY_UI_LEMMY_EXTERNAL_HOST=localhost:1236

Can you tell me what the issue is with it?

Kind regards
Peter



root@vmi2446053:~# cat /lemmy/Lemmy-Easy-Deploy/live/docker-compose.yml
```
x-logging:
  &default-logging
  options:
    max-size: '512m'
  driver: json-file

services:

  proxy:
    build: ./caddy
    mem_limit: 4096m
#    mem_reservation: 2048m
    memswap_limit: 8192m
    cpus: 2
    env_file:
      - ./caddy.env
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - 80:80
      - 443:443
    depends_on:
      - pictrs
      - lemmy-ui
    restart: always
    logging: *default-logging

  lemmy:
    image: dessalines/lemmy:0.19.11
    mem_limit: 4096m
#    mem_reservation: 1536m
    memswap_limit: 8192m
    cpus: 2
    volumes:
      - ./lemmy.hjson:/config/config.hjson
    depends_on:
      - postgres
      - pictrs
    restart: always
    logging: *default-logging

  lemmy-ui:
    image: dessalines/lemmy-ui:0.19.11
    mem_limit: 4096m
#    mem_reservation: 1536m
    memswap_limit: 8192m
    cpus: 3
    environment:
      - LEMMY_UI_LEMMY_INTERNAL_HOST=lemmy:8536
      - LEMMY_UI_LEMMY_EXTERNAL_HOST=localhost:1236
    volumes:
      - ./lemmy-ui-themes:/app/extra_themes
    depends_on:
      - lemmy
    restart: always
    logging: *default-logging

  pictrs:
    image: asonix/pictrs:0.5
    mem_limit: 4096m
#    mem_reservation: 1536m
    memswap_limit: 8192m
    cpu_shares: 512 #default 1024
    cpus: 2
    user: 991:991
    environment:
      - PICTRS__MEDIA__IMAGE__FORMAT=jpeg
      - PICTRS__MEDIA__MAX_FILE_SIZE=5
      - PICTRS__MEDIA__ANIMATION__FORMAT=webp
      - PICTRS__MEDIA__ANIMATION__MAX_FILE_SIZE=10
      - PICTRS__MEDIA__ANIMATION__MAX_WIDTH=256
      - PICTRS__MEDIA__ANIMATION__MAX_HEIGHT=256
      - PICTRS__MEDIA__ANIMATION__MAX_AREA=65536
      - PICTRS__MEDIA__ANIMATION__MAX_FRAME_COUNT=400
      - PICTRS__MEDIA__VIDEO__ENABLE=true
      - PICTRS__MEDIA__VIDEO__ALLOW_AUDIO=true
      - PICTRS__MEDIA__VIDEO__MAX_FILE_SIZE=50
      - PICTRS__MEDIA__VIDEO__VIDEO_CODEC=av1
    env_file:
      - ./pictrs.env
      - ./customPictrs.env
    volumes:
      - pictrs_data:/mnt
    restart: always
    logging: *default-logging

  postgres:
    image: postgres:16-alpine
    mem_limit: 8192m
#    mem_reservation: 3072m
    memswap_limit: 16384m
    cpus: 3
    environment:
      - POSTGRES_USER=<redacted>
      - POSTGRES_DB=<redacted>
    env_file:
      - ./postgres.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./customPostgresql.conf:/etc/postgresql.conf
    restart: always
    shm_size: 6g
    logging: *default-logging


volumes:
  caddy_data:
  caddy_config:
  pictrs_data:
  postgres_data:
```
root@vmi2446053:~#
