### ISSUE TITLE
Video files not working - no MIME Type found when linking to mp4s and "unsupported image"-Error when trying to upload myself

### ISSUE THREAD

**Issue by lcsfox337** [LemmyNet/lemmy-ui#618]
Does anyone know what might be the error?

I tried getting a mp4 to work by manually moving it to the server and it worked just fine, so the problem seems to be with the "Create Post" part, but I haven't managed to find it yet.

Here is my docker-compose.yml  :

```
version: '2.2'

services:
  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    restart: always

  lemmy:
    image: dessalines/lemmy:0.16.3
    ports:
      - "127.0.0.1:8536:8536"
      - "127.0.0.1:6669:6669"
    restart: always
    environment:
      - RUST_LOG="warn,lemmy_server=info,lemmy_api=info,lemmy_api_common=info,lemmy_api_crud=info,lemmy_apub=info,lemmy_db_schema=info,lemmy_db_views=info,lemmy_db_views_act>
    volumes:
      - ./lemmy.hjson:/config/config.hjson
    depends_on:
      - postgres
      - pictrs

  lemmy-ui:
    image: dessalines/lemmy-ui:0.16.3
    ports:
      - "127.0.0.1:1235:1234"
    restart: always
    environment:
      - LEMMY_INTERNAL_HOST=
      - LEMMY_EXTERNAL_HOST=
      - LEMMY_HTTPS=true
    depends_on:
      - lemmy

```
